export const COUNTRIES = [
  { code: 'BR', name: 'Brazil', flag: '🇧🇷', currency: 'BRL' },
  { code: 'AR', name: 'Argentina', flag: '🇦🇷', currency: 'ARS' },
  { code: 'FR', name: 'France', flag: '🇫🇷', currency: 'EUR' },
  { code: 'DE', name: 'Germany', flag: '🇩🇪', currency: 'EUR' },
  { code: 'ES', name: 'Spain', flag: '🇪🇸', currency: 'EUR' },
  { code: 'PT', name: 'Portugal', flag: '🇵🇹', currency: 'EUR' },
  { code: 'GB', name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', currency: 'GBP' },
  { code: 'MX', name: 'Mexico', flag: '🇲🇽', currency: 'MXN' },
  { code: 'US', name: 'USA', flag: '🇺🇸', currency: 'USD' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴', currency: 'COP' },
  { code: 'JP', name: 'Japan', flag: '🇯🇵', currency: 'JPY' },
  { code: 'KR', name: 'South Korea', flag: '🇰🇷', currency: 'KRW' },
  { code: 'NG', name: 'Nigeria', flag: '🇳🇬', currency: 'NGN' },
  { code: 'MA', name: 'Morocco', flag: '🇲🇦', currency: 'MAD' },
  { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦', currency: 'SAR' },
  { code: 'AU', name: 'Australia', flag: '🇦🇺', currency: 'AUD' },
];

export const MATCHES = [
  {
    id: 'm1',
    home: { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
    away: { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
    time: '15:00',
    date: 'Jun 14',
    stadium: 'MetLife Stadium',
    city: 'New York',
    group: 'Group A',
  },
  {
    id: 'm2',
    home: { code: 'MX', name: 'Mexico', flag: '🇲🇽' },
    away: { code: 'ES', name: 'Spain', flag: '🇪🇸' },
    time: '18:00',
    date: 'Jun 14',
    stadium: 'Estadio Azteca',
    city: 'Mexico City',
    group: 'Group B',
  },
  {
    id: 'm3',
    home: { code: 'FR', name: 'France', flag: '🇫🇷' },
    away: { code: 'DE', name: 'Germany', flag: '🇩🇪' },
    time: '20:00',
    date: 'Jun 15',
    stadium: 'SoFi Stadium',
    city: 'Los Angeles',
    group: 'Group C',
  },
];

export const MERCHANTS = [
  {
    id: 'biz1',
    name: 'Tacos El Azteca',
    category: 'food',
    emoji: '🌮',
    description: 'Authentic Mexican street tacos, the best in CDMX. Open since 1978.',
    address: 'Av. Insurgentes Sur 123, CDMX',
    distance: '0.3 km',
    rating: 4.8,
    reviewCount: 247,
    languages: ['🇲🇽 Spanish', '🇺🇸 English'],
    deal: { title: '10% off — Mexico match days!', multiplier: 2 },
    badges: ['⭐ Fan Favorite', '🌍 International Hub'],
    hours: 'Mon–Sun: 8:00 AM – 11:00 PM',
    pointsMultiplier: 2,
    lat: 19.4326,
    lng: -99.1332,
  },
  {
    id: 'biz2',
    name: 'Café Estadio',
    category: 'drinks',
    emoji: '☕',
    description: 'Premium coffee and cocktails. Watch every match on our big screens.',
    address: 'Calle Reforma 456, CDMX',
    distance: '0.7 km',
    rating: 4.6,
    reviewCount: 183,
    languages: ['🇲🇽 Spanish', '🇺🇸 English', '🇧🇷 Portuguese'],
    deal: { title: 'Free shot with every purchase!', multiplier: 3 },
    badges: ['🏆 World Cup Partner'],
    hours: 'Mon–Sun: 6:00 AM – 2:00 AM',
    pointsMultiplier: 3,
    lat: 19.4330,
    lng: -99.1340,
  },
  {
    id: 'biz3',
    name: 'WorldCup Merch Store',
    category: 'merch',
    emoji: '👕',
    description: 'Official licensed FIFA 2026 merchandise. All 48 national team jerseys.',
    address: 'Plaza Reforma 789, CDMX',
    distance: '1.2 km',
    rating: 4.5,
    reviewCount: 92,
    languages: ['🇲🇽 Spanish', '🇺🇸 English', '🇩🇪 German', '🇯🇵 Japanese'],
    deal: null,
    badges: ['🏆 World Cup Partner'],
    hours: 'Mon–Sun: 9:00 AM – 9:00 PM',
    pointsMultiplier: 1,
    lat: 19.4320,
    lng: -99.1325,
  },
  {
    id: 'biz4',
    name: 'Hotel Azteca Suites',
    category: 'hotel',
    emoji: '🏨',
    description: 'Boutique hotel 5 min from Estadio Azteca. Fan packages available.',
    address: 'Calzada de Tlalpan 321, CDMX',
    distance: '2.1 km',
    rating: 4.7,
    reviewCount: 156,
    languages: ['🇲🇽 Spanish', '🇺🇸 English', '🇫🇷 French'],
    deal: { title: 'Match day package — breakfast included', multiplier: 2 },
    badges: ['⭐ Fan Favorite', '🌍 International Hub'],
    hours: '24/7',
    pointsMultiplier: 2,
    lat: 19.4310,
    lng: -99.1350,
  },
];

export const REVIEWS = [
  {
    id: 'r1',
    fanFlag: '🇧🇷',
    fanCountry: 'Brazil',
    rating: 5,
    text: 'Incredible tacos! Worth every penny. The staff was super welcoming and they even cheered for Brazil with us! 100% recommend.',
    date: 'Jun 14, 2026',
    verified: true,
    photo: null,
    businessResponse: 'Thank you! Viva Brasil! 🎉 We loved having you!',
  },
  {
    id: 'r2',
    fanFlag: '🇩🇪',
    fanCountry: 'Germany',
    rating: 4,
    text: 'Great food, very authentic. Prices are fair for a tourist area. Long wait but worth it.',
    date: 'Jun 13, 2026',
    verified: true,
    photo: null,
    businessResponse: null,
  },
  {
    id: 'r3',
    fanFlag: '🇯🇵',
    fanCountry: 'Japan',
    rating: 5,
    text: 'Best experience in Mexico City! The staff helped us understand the menu. Amazing spicy tacos!',
    date: 'Jun 12, 2026',
    verified: true,
    photo: null,
    businessResponse: 'Arigatou! 🙏 Come back anytime!',
  },
];

export const TRANSACTIONS = [
  { id: 't1', merchant: 'Tacos El Azteca', emoji: '🌮', amount: 12.5, points: 13, date: 'Today, 14:32', status: 'confirmed' },
  { id: 't2', merchant: 'Café Estadio', emoji: '☕', amount: 8.0, points: 24, date: 'Today, 11:15', status: 'confirmed' },
  { id: 't3', merchant: 'WorldCup Merch Store', emoji: '👕', amount: 65.0, points: 65, date: 'Yesterday', status: 'confirmed' },
  { id: 't4', merchant: 'Hotel Azteca Suites', emoji: '🏨', amount: 120.0, points: 240, date: 'Jun 12', status: 'confirmed' },
];

export const STAMPS = [
  { id: 's1', emoji: '🏟️', name: 'Estadio Azteca', description: 'Visited the iconic stadium', earned: true, date: 'Jun 14' },
  { id: 's2', emoji: '🌆', name: 'Ciudad de México', description: 'Explored Mexico City', earned: true, date: 'Jun 12' },
  { id: 's3', emoji: '🌮', name: 'Taco Explorer', description: 'Visited 3 food merchants', earned: true, date: 'Jun 13' },
  { id: 's4', emoji: '📝', name: 'First Review', description: 'Left your first verified review', earned: true, date: 'Jun 14' },
  { id: 's5', emoji: '💳', name: 'First Payment', description: 'Made your first FanWallet payment', earned: true, date: 'Jun 12' },
  { id: 's6', emoji: '🏟️', name: 'MetLife Stadium', description: 'Visit MetLife Stadium', earned: false, date: null },
  { id: 's7', emoji: '🌆', name: 'Los Angeles', description: 'Explore the City of Angels', earned: false, date: null },
  { id: 's8', emoji: '🌍', name: 'Globe Trotter', description: 'Visit 10 different merchants', earned: false, date: null },
  { id: 's9', emoji: '💰', name: 'High Roller', description: 'Spend $500 total', earned: false, date: null },
  { id: 's10', emoji: '⭐', name: 'Super Scout', description: 'Leave 10 verified reviews', earned: false, date: null },
];

export const RECENT_BIZ_TRANSACTIONS = [
  { id: 'bt1', fanFlag: '🇧🇷', fanCountry: 'Brazil', amount: 12.50, points: 25, time: '14:32', items: 'Tacos x3' },
  { id: 'bt2', fanFlag: '🇩🇪', fanCountry: 'Germany', amount: 8.00, points: 16, time: '14:18', items: 'Drinks x2' },
  { id: 'bt3', fanFlag: '🇯🇵', fanCountry: 'Japan', amount: 21.00, points: 42, time: '13:55', items: 'Combo meal' },
  { id: 'bt4', fanFlag: '🇫🇷', fanCountry: 'France', amount: 15.50, points: 31, time: '13:30', items: 'Tacos x4, Drink' },
  { id: 'bt5', fanFlag: '🇦🇷', fanCountry: 'Argentina', amount: 9.00, points: 18, time: '12:45', items: 'Burrito x1' },
];

export const ANALYTICS_DATA = {
  today: { revenue: 312.50, transactions: 28, avgTx: 11.16, newFans: 19, returningFans: 9 },
  week: { revenue: 2840.00, transactions: 187, avgTx: 15.19, newFans: 134, returningFans: 53 },
  tournament: { revenue: 18920.00, transactions: 1043, avgTx: 18.14, newFans: 721, returningFans: 322 },
  countries: [
    { flag: '🇧🇷', country: 'Brazil', count: 89, revenue: 1240 },
    { flag: '🇩🇪', country: 'Germany', count: 67, revenue: 980 },
    { flag: '🇯🇵', country: 'Japan', count: 54, revenue: 840 },
    { flag: '🇫🇷', country: 'France', count: 48, revenue: 720 },
    { flag: '🇦🇷', country: 'Argentina', count: 43, revenue: 610 },
    { flag: '🇰🇷', country: 'South Korea', count: 38, revenue: 540 },
  ],
  hourly: [
    { hour: '10', rev: 45 }, { hour: '11', rev: 78 }, { hour: '12', rev: 120 },
    { hour: '13', rev: 98 }, { hour: '14', rev: 145 }, { hour: '15', rev: 189 },
    { hour: '16', rev: 210 }, { hour: '17', rev: 178 }, { hour: '18', rev: 234 },
    { hour: '19', rev: 198 }, { hour: '20', rev: 156 }, { hour: '21', rev: 89 },
  ],
};
